# Example FUNDING.yml

github: [CodedMyst]  # GitHub Sponsors username
patreon: mystic_coder   # Patreon username
open_collective: mystic_collector  # Open Collective username
ko_fi: mysticcoder  # Ko-fi username
tidelift: mystic-package  # Tidelift project slug
community_bridge: mystic-project  # Linux Foundation ID
liberapay: mystic_community  # Liberapay username
custom: ["https://mywebsite.com/donate"]  # Custom donation link
